# serverless.yml

service: KKCreationBackend

custom: # add these two lines
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    MONGODB_URL: ${self:custom.secrets.MONGODB_URL}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    PORT: ${self:custom.secrets.PORT}
    MY_AWS_ACCESS_KEY_ID: ${self:custom.secrets.MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${self:custom.secrets.MY_AWS_SECRET_ACCESS_KEY}

functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true